### PR TITLE
Added "Wagtail Blocks" to StreamField section

### PR DESCRIPTION
**Pull request by ibrahimawadhamid**
[Wagtail Blocks](https://github.com/ibrahimawadhamid/wagtail_blocks), A Collection of awesome Wagtail CMS stream-field blocks.

### CODE REVIEW

**Comment by ibrahimawadhamid** [comment]
@mojeto  why is this pending ? Am I doing something wrong ?

**Comment by KalobTaulien** [comment]
> @mojeto why is this pending ? Am I doing something wrong ?

No you're probably not doing anything wrong, it's just the weekend. This repo also requires at least one review first. I'm not a contributor to this repo so I won't step in, but I didn't want you to feel like you've been left out :)

**Review by mojeto — APPROVED** [review]
Hi @ibrahimawadhamid 
all good on your end. Thank you for you contribution and patience.

**Comment by mojeto** [comment]
Thanks @KalobTaulien for stopping by and leaving kind words.

**Comment by ibrahimawadhamid** [comment]
@KalobTaulien thanks Kalob ! that's nice of you .

**Pull request merged**
