### PR TITLE
Add Wagtail Space 2018 presentations

### PR DESCRIPTION
**Pull request by thibaudcolas**
All of the presentations from YouTube, linked directly to the right start mark 🌈

- [How Google uses Wagtail](https://www.youtube.com/watch?v=lh9nmN1mzwQ&t=1937s) by Kevin Chung.
- [Introducing Draft.js in Wagtail](https://www.youtube.com/watch?v=lh9nmN1mzwQ&t=2690s) by Thibaud Colas. [Presentation](http://thib.me/introducing-draft-js-in-wagtail)
- [Let It Go](https://www.youtube.com/watch?v=lh9nmN1mzwQ&t=3938s) by Matt Wescott.
- [Developing Solutions for Girls, by Men](https://www.youtube.com/watch?v=lh9nmN1mzwQ&t=5184s) by Lisa Adams.
- [Wagtail’s first hatch](https://www.youtube.com/watch?v=P8RUQE7Djdg&t=265s) by Bertrand Bordage.
- [The Word Problem](https://www.youtube.com/watch?v=P8RUQE7Djdg&t=2841s) by Tom Dyson.
- [Wagtail on Divio Cloud](https://www.youtube.com/watch?v=P8RUQE7Djdg&t=3856s) by Daniele Procida.
- [Chopping the head off Wagtail and sticking it back on](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=152s) by Tony Yates.
- [StreamField editor at UWKM](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=400s) by Geert jan Hoogeslag.
- [Things i learned at wagtail space](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=719s) by Codie Roelf.
- [Fly Wagtail to a PyCon](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=912s) by Daniele Procida.
- [Wagtail Performance](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=1345s) by Michael van Tellingen. [Code](https://gist.github.com/mvantellingen/daebda6abbaa9a5ed0888f886a77fcf0).
- [Mutliple images uploader](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=1661s) by Rajeev J Sebastian.
- [Wagtail Space easter egg team demo](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=2057s) by Lars.
- [Wagtail Space 2019](https://www.youtube.com/watch?v=u0CPaXRSOzI&t=2278s) by Maarten Kling.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
I'm sorry, but, what's about sliders or code :(?

**Comment by thibaudcolas** [comment]
@SalahAdDin yeah I know 😞 

I have added the ones I know about, unfortunately it's very few. We'd need to ask all the speakers separately, and that's more work than I can commit right now.

**Comment by SalahAdDin** [comment]
@thibaudcolas I would be awesome, i'm viewing all presentations.

**Comment by allcaps** [comment]
Wagtail Space easter egg team demo by Lars. => https://github.com/specialunderwear/haunted-wagtail

Wagtail’s first hatch by Bertrand Bordage. => https://www.kickstarter.com/projects/noripyt/wagtails-first-hatch

**Pull request merged**
