### PR TITLE
Add Getting started with Draftail extensions

### PR DESCRIPTION
**Pull request by thibaudcolas**
https://thib.me/getting-started-with-draftail-extensions

A short "getting started" article which answers the basic questions.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@thibaudcolas It will be awesome if you teach us how implement that util plugins.

I'm interesting, practically, in all the plugins.

**Comment by thibaudcolas** [comment]
@SalahAdDin 👌 do you have a specific example you'd like me to cover? I'm looking for some ideas to further demonstrate those APIs.

**Comment by SalahAdDin** [comment]
All plugins about count: count words, characters, etc. I would be great.

**Comment by thibaudcolas** [comment]
👍 I'll make a tutorial about those

**Comment by SalahAdDin** [comment]
@thibaudcolas thank you

**Pull request merged**
