### PR TITLE
Add article comparing Drupal & Wagtail

### PR DESCRIPTION
**Pull request by lb-**
Relatively recent (October 2018) and well laid out article that would be helpful to those coming from Drupal

### CODE REVIEW

**Review by mojeto — APPROVED** [review]
thank you

**Comment by mojeto** [comment]
@lb- can you resolve the merge conflict by updating your branch with current master please?

**Comment by lb-** [comment]
@mojeto - thanks, should be good now

**Comment by mojeto** [comment]
thanks

**Pull request merged**
